name: markdown-to-respec
description: publish specifications written in Markdown files as ReSpec HTML
inputs:
  publish_branch:
    description: 'The git branch to publish HTML to.'
    required: true
    default: 'gh-pages'
  markdown_dir:
    description: 'The directory containing Markdown files.'
    required: true
    default: '.'
  ignore:
    description: 'A regex of Markdown files to ignore.'
    required: false
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r '${{ github.action_path }}/requirements.txt'
    - name: Generate ReSpec
      shell: bash
      run: |
        python3 "${{ github.action_path }}/markdown_to_respec.py" \
                "${{ inputs.markdown_dir }}" \
                --branch "${{ inputs.publish_branch }}" \
                --ignore "${{ inputs.ignore }}"
