name: respec-action
description: publish specifications written in Markdown files as ReSpec HTML
inputs:
  publish_branch:
    description: 'The git branch to publish HTML to.'
    required: true
    default: 'gh-pages'
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Pip
      shell: bash
      run: |
        pip install poetry
        poetry install
    - name: Generate ReSpec
      shell: bash
      run: poetry run ./respec_action.py
    - name: Publish
      shell: bash
      run: |
        git config user.name "respec-action"
        git config user.email "<>"

        git switch "${{ inputs.publish_branch }}"
        if [ $? -ne 0 ]; then
          git switch -c "${{ inputs.publish_branch }}"
        fi

        git add .
        if [ $? -eq 0 ]; then
          git commit -m "Latest ReSpec HTML"
          git push origin "${{ inputs.publish_branch }}"
        else
          echo "No ReSpec HTML needed publishing"
        fi
