name: respec-action
description: publish specifications written in Markdown files as ReSpec HTML
inputs:
  publish_branch:
    description: 'The git branch to publish HTML to.'
    required: true
    default: 'gh-pages'
  markdown_dir:
    description: 'The directory containing Markdown files.'
    required: true
    default: '.'
runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r '${{ github.action_path }}/requirements.txt'
    - name: Generate ReSpec
      shell: bash
      run: python3 "${{ github.action_path }}/respec_action.py" "${{ inputs.markdown_dir }}" --branch "${{ inputs.publish_branch }}"
