name: Test Action
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Builds the ReSpec HTML
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: ls
        run: 
          - "ls -al"
      - name: Run respec_action
        uses: ./
